name: Deploy测试
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: ls -la
    - run: echo "Hello World" && echo $SHELL
    - run: node -v
    - run: curl -fsSL https://bun.sh/install | bash
    # - run: export PATH=$PATH:$HOME/.bun/bin
    - run: echo "PATH=$PATH:$HOME/.bun/bin" >> $GITHUB_ENV
    - run: echo $PATH
    - run: bun -v