name: Deployæµ‹è¯•
run-name: ${{ github.actor }} started a deployment
permissions:
  contents: write
on: 
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    # container: oven/bun:1.3-alpine
    steps:
    - run: pwd
    - run: ls -la
    # - name: Setup Git
    #   run: |
    #     apk add git
    #     git version
    - run: echo "Hello World" && echo $SHELL && echo $HOME
      name: è¾“å‡ºæŒ‡å®šçŽ¯å¢ƒå˜é‡
    - run: curl -fsSL https://bun.sh/install | bash
    - run: echo "PATH=$PATH:$HOME/.bun/bin" >> $GITHUB_ENV
    - run: bun -v
    - uses: actions/checkout@v6
    - run: bun install
    - run: VITE_ROUTER_BASENAME=/github-actions-test bun run -b build
    - run: ls -la
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
    # - run: node -v
    # - run: curl -fsSL https://bun.sh/install | bash
    # - run: export PATH=$PATH:$HOME/.bun/bin
    # - run: echo "PATH=$PATH:$HOME/.bun/bin" >> $GITHUB_ENV
    # - run: echo $PATH
    # - run: bun -v
