name: Deploy测试
run-name: ${{ github.actor }} started a deployment
permissions:
  contents: write
on: 
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    container: oven/bun:1.3-alpine
    steps:
    - run: pwd
    - run: ls -la
    - run: echo "Hello World" && echo $SHELL && echo $HOME
      name: 输出指定环境变量
    - run: bun -v
    - uses: actions/checkout@v6
    - run: |
        bun install
        bun run build
    # - run: node -v
    # - run: curl -fsSL https://bun.sh/install | bash
    # - run: export PATH=$PATH:$HOME/.bun/bin
    # - run: echo "PATH=$PATH:$HOME/.bun/bin" >> $GITHUB_ENV
    # - run: echo $PATH
    # - run: bun -v